# NumPy
*  NumPy is an open source library available in Python that hepls
  in mathematical, scientific, engineering, and data science
  programming.
* It works perfectly well for multi-dimensional arrays and
  matrices multiplication.
* TensorFlow and Scikit learn to use NumPy array to compute
  the matrix multiplication in the back end.
*  NumPy is memory efficiency, meaning it can handle the vast
  amount of data more accessible than any other library.


# How to Install NumPy?




```bash
pip install numpy
```


In [1]:
# To check numpy installed or not 
import numpy as np
print (np.__version__)


2.2.6


# Python Numpy Array

* NumPy arrays are a bit like Python lists, but still very much
different at the same time.

* The library’s name is actually short for "Numeric Python" or
"Numerical Python".


In [2]:
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)
# we have commas

[1, 2, 3, 4, 5]


list

In [3]:
import numpy as np
Lists = [1,2,3,4,5]

a = np.array(Lists)

print(a)
print("the type is :",type(a))

[1 2 3 4 5]
the type is : <class 'numpy.ndarray'>


In [4]:
#addition 
numpy_array = np.array([1,2,3,4,5,6,7,8,9])
numpy_array +1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#substraction
numpy_array-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#multiplication
numpy_array*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
#division
numpy_array/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# checking shapes, dtypes, and dimension of numpy array

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.shape)
print(a.dtype)
print(a.ndim)

(8,)
int64
1


In [9]:
b = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [10]:
ar = np.array([(1,2,3,4,5,6),
              (4,5,6,7,8,7)])
print(ar)
print(ar.shape)


[[1 2 3 4 5 6]
 [4 5 6 7 8 7]]
(2, 6)


In [11]:
ar = np.array([
    [[1, 2, 3, 6, 7],
     [4, 5, 6, 6, 8]],

    [[7, 8, 9, 0, 0],
     [10, 11, 12, 8, 3]],
    
    [[7, 8, 9, 0, 0],
     [10, 11, 12, 8, 3]],
    
])

print(ar.shape)

(3, 2, 5)


# creating numpy array with zeros and ones

In [16]:
import numpy as np
np.zeros((2))

array([0., 0.])

In [12]:
np.ones((3,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Generating the odd Num from 1-10 using numpy

In [13]:
oddnumber = np.arange(1, 11, 2) 
print(oddnumber)

[1 3 5 7 9]


# reshaping the dimentions in numpy array
*product of new shape dimensions = total number of elements*

In [15]:
import numpy as np

e = np.array([(1,2,3),
              (4,5,6)])

reshape_e=e.reshape(3,2)

print("original:",e,"\n")
print("after reshape:",reshape_e)

original: [[1 2 3]
 [4 5 6]] 

after reshape: [[1 2]
 [3 4]
 [5 6]]


In [16]:
import numpy as np
e = np.array([(1,2,3), 
              (4,5,6)])

reshape_e=e.reshape(-1)  # 1D array

print("original:",e,"\n")
print("after reshape:",reshape_e)

original: [[1 2 3]
 [4 5 6]] 

after reshape: [1 2 3 4 5 6]


# flat the numpy array

In [17]:
import numpy as np
a = np.array([(1,2,3), 
              (4,5,6)]) 
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
import numpy as np
a = np.array([(1,2,3), (4,5,6)])
a.ravel()

array([1, 2, 3, 4, 5, 6])

# Stackings on numpy array

In [19]:
# With hstack we can appened data horizontally.

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a:",a,"\n")
print("b:",b,"\n")
print('Horizontal Append:', np.hstack((a, b)))


a: [1 2 3] 

b: [4 5 6] 

Horizontal Append: [1 2 3 4 5 6]


In [30]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a, "\n")
print("b:", b, "\n")

print("Vertical Stack:")
print(np.vstack((a, b)))

a: [1 2 3] 

b: [4 5 6] 

Vertical Stack:
[[1 2 3]
 [4 5 6]]


# generating random numbers

In [23]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2)) # no need to give size param

[[0.97690743 0.4677022 ]
 [0.24905653 0.50880073]]


In [24]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

[[1.13826402 1.20047309]
 [0.32464849 1.3558093 ]]


In [29]:
# Random integers between [100, 500] of shape 2,2
print(np.random.randint(1, 6, size=[2,2]))

[[5 1]
 [2 3]]


In [26]:
# One random number between [0,1)
print(np.random.random(1))

[0.06489601]


In [30]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[0.2615585  0.42611349]
 [0.87165756 0.97097845]]


In [31]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=(3)))

['u' 'e' 'i']


In [32]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=3, p=[0.3, 0.1,0.1, 0.4, 0.1]))

['e' 'o' 'u']


# Basic Statistics on numpy array

In [33]:
normal_array = np.random.randn(3, 3)

# Min
print("Min:", np.min(normal_array))

# Max
print("Max:", np.max(normal_array))

# Mean
print("Mean:", np.mean(normal_array))

# Median
print("Median:", np.median(normal_array))

# Standard Deviation
print("Std:", np.std(normal_array))

Min: -0.3225941371033736
Max: 2.943052111575596
Mean: 0.875546883454271
Median: 0.5669911414714174
Std: 0.9842617035276329


# Matrix Operations
* In many instances, numpy arrays can
  be thought of as matrices.
*  In the next slides we explore some matrix
  operations on numpy arrays.


In [34]:
# The determinant of an array
import scipy.linalg as slin
import numpy as np

a = np.array([[ 3, -5, 8],
 [-1, 2, 3],
 [-5, -6, 2]])

print(slin.det(a))

259.0


In [36]:
#The trace of an array is found by using the trace() function from numpy.

import numpy as np

a = np.array([[ 3, -5, 8],
             [-1, 2, 3],
            [-5, -6, 2]])

print(np.trace(a))


7


In [37]:
# Inverse of a matrix is computed from scipy.linalg.inv() function
import scipy.linalg as slin
import numpy as np
a = np.array([[ 3, -5, 8],
                [-1, 2, 3],
               [-5, -6, 2]])
slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

In [38]:
import numpy as np
a = np.array([[ 3, -5, 8],
           [-1, 2, 3],
           [-5, -6, 2]])
np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

## for multiplication we this is needed (m, n) × (n, p) → (m, p)

In [39]:
import numpy as np
a=np.matrix([[ 3, -5, 8],
             [ 3, -5, 8],
            [-1, 2, 3],
           [-5, -6, 2]])

print(a.shape)

b=np.matrix([[ 3],
           [ 4],
           [-1]])

print(b.shape)
 
c=a*b

print(c.shape)

c

(4, 3)
(3, 1)
(4, 1)


matrix([[-19],
        [-19],
        [  2],
        [-41]])